name: dotnet-docker-heroku CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

#set environment variables
env:
  HEROKU_API_KEY: 227b528f-a925-4ad3-b3eb-592b5761ff91
  APP_NAME: apilooback

jobs:

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-18.04
    steps:

    # Clone the repository
    - name: Checkout
      uses: actions/checkout@v2

    # Build Docker image
    - name: Docker build
      run: docker login --username=prodinshape@gmail.com --password=$HEROKU_API_KEY registry.heroku.com

    # Push the Docker image to Heroku Container Registry
    - name: Publish
      run: |
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
