# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # - name: Build, Push and Release a Docker container to Heroku.
      #   # You may pin to the exact commit or the version.
      #   # uses: gonuit/heroku-docker-deploy@9ab97585f979857642d66612a2ae4062b3347d53
      #   uses: gonuit/heroku-docker-deploy@v1.3.3
      #   with:
      #     # Name of the heroku application to which the build is to be sent.
      #     heroku_app_name: apilooback
      #     # The email address associated with your Heroku account.
      #     email: prodinshape@gmail.com
      #     # Heroku API key associated with provided user's email.
      #     heroku_api_key: 227b528f-a925-4ad3-b3eb-592b5761ff91
      #     # Dockerfile directory.
      #     dockerfile_directory: ./apps/apilooback/
      #     # Dockerfile name. [default=Dockerfile]
      #     dockerfile_name: Dockerfile
      #     # Select process type for wich you want docker container to be uploaded. [default=web]
      #     process_type: web

      # - name: Deploy to Heroku Using Docker
      #   # You may pin to the exact commit or the version.
      #   # uses: mtsmachado8/heroku-deploy@5bf18e5f6160beaccc01c678d0aaa81963434e74
      #   uses: mtsmachado8/heroku-deploy@v2.0.3
      #   with:
      #     # Email Linked to your Heroku Account
      #     email: prodinshape@gmail.com
      #     # Your Heroku API Key
      #     api_key: 227b528f-a925-4ad3-b3eb-592b5761ff91
      #     # Your Heroku App Name
      #     app_name: apilooback
      #     # Dokerfile path
      #     dockerfile_path: ./apps/apilooback
      # - name: Deploy Multiple Docker Images to Heroku Apps
      #   # You may pin to the exact commit or the version.
      #   # uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@a4590bf326a12190449bdd4c07657e048b1ca9d7
      #   uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0
      #   with:
      #     # Email linked to your Heroku account
      #     email: prodinshape@gmail.com
      #     # Your Heroku API Key
      #     api_key: 227b528f-a925-4ad3-b3eb-592b5761ff91
      #     # Your Heroku App Name
      #     app_name: apilooback
      #     # docker-compose File Path
      #     docker_compose_file: apps/apilooback/Dockerfile
      # - name: Heroku Docker Container Deploy
        # You may pin to the exact commit or the version.
        # uses: lucassarcanjo/heroku-deploy@1db4c62f6032efe526c12734f18d36669218e5af
        # uses: lucassarcanjo/heroku-deploy@2.1.17
        # with:
        #   # Email Linked to your Heroku Account
        #   email: prodinshape@gmail.com
        #   # Heroku Dyno Formation
        #   formation: web
        #   # Your Heroku API Key
        #   api_key: 227b528f-a925-4ad3-b3eb-592b5761ff91
        #   # Your Heroku App Name
        #   app_name: apilooback
        #   # Dokerfile path
        #   dockerfile_path: apps/apilooback
        - name: Deploy to Heroku Using Docker Container
          # You may pin to the exact commit or the version.
          # uses: cloutojp/heroku-deploy@bc1a3d9259ed8138863809a6ed11b3bae18ff6ba
          uses: cloutojp/heroku-deploy@v2.0.7
          with:
            # Email Linked to your Heroku Account
            email: prodinshape@gmail.com
            # Your Heroku API Key
            api_key: 227b528f-a925-4ad3-b3eb-592b5761ff91
            # Your Heroku App Name
            app_name: apilooback
            # Dokerfile path
            dockerfile_path: ./apps/apilooback
